[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 150
let g:deoplete#auto_complete_start_length = 1

'''

[[plugins]]
repo = 'fatih/vim-go'

#[[plugins]]
#repo = 'pangloss/vim-javascript'

#[[plugins]]
#repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'typewriter/zenrei.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nmap <silent> <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
      \ 'cpp': ['clangd'],
      \ 'ruby': ['solargraph', 'stdio'],
      \ 'python': ['pyls'],
      \ 'javascript': ['javascript-typescript-stdio'],
      \ 'javascript-jsx': ['javascript-typescript-stdio'],
      \ 'vue': ['vls'],
      \ }
let g:LanguageClient_loadSettings = 1

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
" Or map each action separately
nnoremap <silent> F :call LanguageClient#textDocument_formatting()<CR>
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''
hook_source = '''
set completefunc=LanguageClient#complete
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
if = 'has("nvim")'
hook_source = 'source ~/.config/nvim/userautoload/plugins/plugins-denite.vim'
hook_add = '''
nmap <silent> <C-p> :<C-u>Denite file_rec<CR>
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd   ctermbg=22
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven  ctermbg=18
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=250
set signcolumn=yes
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''
# [[plugins]]
# repo = 'w0rp/ale'
# hook_add = '''
# let g:ale_set_highlights = 0
# let g:ale_sign_error = ' '
# let g:ale_sign_warning = ' '
# '''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'

hook_add = '''
let g:airline_theme = 'wombat'
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#wordcount#enabled = 0
let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
let g:airline_section_c = '%F'
let g:airline_section_x = '%{&filetype}'
let g:airline_section_z = '%3l:%2v %{airline#extensions#ale#get_warning()} %{airline#extensions#ale#get_error()}'
let g:airline#extensions#ale#error_symbol = ' '
let g:airline#extensions#ale#warning_symbol = ' '
let g:airline#extensions#default#section_truncate_width = {}
let g:airline#extensions#whitespace#enabled = 1
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

